### ISSUE TITLE
Android doesn't parse valid regex correctly

### ISSUE THREAD

**Issue by CryoliteDev** [Katsute/Mal4J#133]
hey,

When writing a CLI app using Java 11 and maven(1.1.1) I can get the the API to work fine.

However, when I try and use the API in an android app using Java 11 and gradle(1.1.1). It throws an: `java.lang.ExceptionInInitializerError`
![image](https://user-images.githubusercontent.com/60494759/111332447-2e732f00-8648-11eb-8b2e-5736d4aaaad1.png)

This is the code that I am using:
![image](https://user-images.githubusercontent.com/60494759/111332686-611d2780-8648-11eb-9a80-d34fefcd992b.png)

Was wondering if it's some sort of compatibility issue with the API on android or if I need to be looking elsewhere?

**Comment by Katsute** [comment]
The issue seems to be caused by android using a different regex engine than on desktop, specifically it is failing to interpret `}` as `\}`. I will create a patch for this bug.

**Comment by Katsute** [comment]
Fixed in `1.1.2`. Please let me know if any more issues occur.

**Comment by CryoliteDev** [comment]
`java.lang.NoSuchMethodError: No static method encode(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String; in class Ljava/net/URLEncoder; or its super classes (declaration of 'java.net.URLEncoder' appears in /system/framework/core-oj.jar)`

![image](https://user-images.githubusercontent.com/60494759/111412181-4da6a680-86b2-11eb-8f72-e05ee594e1d0.png)

do you perhaps have instructions on how to build the JAR file for android and/or if you have an example of using JAR on android

**Comment by Katsute** [comment]
That issue seems to be caused by a missing method in the jdk, is the android running jdk11?

**Comment by Katsute** [comment]
The root cause seems to be the fact that android accepts jars compiled in Java 11 while only allowing the Java 7~8 API. 

I have opened a new issue and have marked this as a feature. #137
