### ISSUE TITLE
URLEncoder

### ISSUE THREAD

**Issue by CryoliteDev** [Katsute/Mal4J#153]
![image](https://user-images.githubusercontent.com/60494759/113481521-049f7200-9468-11eb-9602-fda1a0251f6f.png)

I think `StandardCharsets.UTF_8` needs to be converted to a string:  `StandardCharsets.UTF_8.displayName()`

**Comment by Katsute** [comment]
This issue is caused by android only having access to the Java 8 API (this library currently supports Java 11+). An update is coming out in a few days to bring support to Java 8+.

**Comment by CryoliteDev** [comment]
awesome thx 💯
