### ISSUE TITLE
Opening/Ending Themes are NULL

### ISSUE THREAD

**Issue by CryoliteDev** [Katsute/Mal4J#196]
No matter which anime i search up, its opening/ending themes are null even though the MAL website has them listed. 
API Version: 2.2.0

Code: 
```
OpeningTheme[] openingThemes = search.get(i).getOpeningThemes();
for (OpeningTheme openingTheme : openingThemes) {
     System.out.println(openingTheme.getText());
}
```
Output: ``` null```

Not sure if I'm doing something wrong.

**Comment by Katsute** [comment]
It seems that search queries don't return op/ed fields. I will have to make a change so that all queries return the preview objects instead of the full object.

In order to retrieve the op/ed fields it is likely that you will have to use `MyAnimeList.getAnime(search.get(i).getID())`
