### ISSUE TITLE
Cannot update watchlist anime/manga status without giving priority and rewatch/reread value (NPE)

### ISSUE THREAD

**Issue by fbaierl** [Katsute/Mal4J#254]
### Prerequisites

- [X] I have checked that no other similar issue already exists.
- [X] I have checked that this issue is actually a bug and not a feature.
- [X] I have checked the [documentation](https://mal4j.katsute.dev/).
- [X] I have checked the [FAQ](https://github.com/Katsute/Mal4J/blob/main/faq.md).
- [X] I am running the latest release version.

### Operating System

Android 11

### Java Runtime

Android

### Java Version

Java 8

### Release Version

2.4.0

### Issue

At the moment, it is not possible to update a user list anime/manga status without also giving values for `rereadValue` and `priority`. When trying to call the `update()` method without those parameters, a null-pointer exception is being thrown. E.g.:

```
E/WatchlistRepository: Can't delete anime.
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.kttdevelopment.mal4j.property.Priority.value()' on a null object reference
        at com.kttdevelopment.mal4j.MyAnimeListImpl$5.lambda$update$0$MyAnimeListImpl$5(MyAnimeListImpl.java:317)
        at com.kttdevelopment.mal4j.-$$Lambda$MyAnimeListImpl$5$gHvnSGCtHfzfog7CUl6ip85J39U.get(Unknown Source:2)
        at com.kttdevelopment.mal4j.MyAnimeListImpl.handleResponseCodes(MyAnimeListImpl.java:779)
        at com.kttdevelopment.mal4j.MyAnimeListImpl.handleResponse(MyAnimeListImpl.java:773)
        at com.kttdevelopment.mal4j.MyAnimeListImpl.access$000(MyAnimeListImpl.java:57)
        at com.kttdevelopment.mal4j.MyAnimeListImpl$5.update(MyAnimeListImpl.java:307)
        at com.kttdevelopment.mal4j.MyAnimeListImpl$5.update(MyAnimeListImpl.java:303)
        at ...
        at ...
        at java.lang.Thread.run(Thread.java:923)
``` 

The [official API](https://myanimelist.net/apiconfig/references/api/v2#operation/anime_anime_id_my_list_status_put) gives an example without those values, so it should be possible:

```
curl 'https://api.myanimelist.net/v2/anime/17074/my_list_status' \
-X PUT \
-d status=completed \
-d score=8 \
-d num_watched_episodes=3 \
-H 'Authorization: Bearer YOUR_TOKEN'
```

### Code

```Java
// working
MyAnimeList.withOAuthToken(token)
	.updateMangaListing(malId)
        .status(MangaStatus.Reading)
        .rereadValue(RereadValue.Medium)
        .priority(Priority.Low)
        .update();

// not working (NPE)
MyAnimeList.withOAuthToken(token)
	.updateMangaListing(malId)
        .status(MangaStatus.Reading)
        .update();
```

**Comment by Katsute** [comment]
cause:

https://github.com/Katsute/Mal4J/blob/3a435a9c88449866edb8501993c073aa1790b448/src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java#L317

https://github.com/Katsute/Mal4J/blob/3a435a9c88449866edb8501993c073aa1790b448/src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java#L319

https://github.com/Katsute/Mal4J/blob/3a435a9c88449866edb8501993c073aa1790b448/src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java#L646

https://github.com/Katsute/Mal4J/blob/3a435a9c88449866edb8501993c073aa1790b448/src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java#L648

null ternary is missing

fix:

https://github.com/Katsute/Mal4J/blob/3a435a9c88449866edb8501993c073aa1790b448/src/main/java/com/kttdevelopment/mal4j/MyAnimeListImpl.java#L639

**Comment by Katsute** [comment]
@sinon-bot branch fix null update enum
